Fix SyntaxError in auth_utils.py exchange_code_for_session
Removed stray 'parameter' word causing syntax error on line 114.
This was breaking Google OAuth login with:
SyntaxError: invalid syntax. Perhaps you forgot a comma?

Function signature should be:
def exchange_code_for_session(auth_code: str, code_verifier: str = None, redirect_uri: str = None)

Not:
def exchange_code_for_session(..., redirect_uri: str = None parameter)